### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by iaK** [faph/icalendar-validator#4]
Hi!

Sorry, i'm probably an idiot, but how do i run this?

I have cloned the repo, and ran the docker run command provided in the readme. 

```bash
docker run --volume=/Users/i/Project/icalendar-validator/data:/data --platform=linux/amd64 faph/icalendar-validator /data/ical.ics
```

I've put the file ical.ics in a the data directory. If i connect to the docker container the file has been synced, so no issue there.

Is the docker run command supposed to give output? or am i supposed to run something in the container itself?

Running on an m1 mac.

Thanks a lot!

**Comment by faph** [comment]
Please replace screenshot with actual text

**Comment by iaK** [comment]
```bash
docker run --volume=/Users/i/Project/icalendar-validator/data:/data --platform=linux/amd64 faph/icalendar-validator /data/ical.ics
```

**Comment by faph** [comment]
To be sure, you're running with the Docker image taken from Docker Hub at https://hub.docker.com/r/faph/icalendar-validator?

Is there no output whatsoever?

Try with additional arguments like `--verbose`, `--help`. That kind of debugging might suggest something.

**Comment by faph** [comment]
Additionally, did you inspect the exit code? It may well be that there is no output in case the document is valid. You should get a zero exit code in that case.
