### ISSUE TITLE
Provide a normal jar executable.

### ISSUE THREAD

**Issue by navid-zamani** [faph/icalendar-validator#5]
Nobody wants to install any containerism to just run what is just a tiny program.

Can you just build it to normal bytecode and package and release it as a normal jar executable for people to run?

Alternatively, I recommend at least going full SillyCon Valley luddite techie, and renting some Google cloud to run Windows 11 inside a VM inside Electron (c.f. copy.sh/v86/) on a ChromeOS instance connected to a smart fridge edge computer, so you can implement the blockchain AI component to your nice OS and please Elon Musk’s very *strongly* shaped … rocket. 😋

**Comment by faph** [comment]
Just use this: https://github.com/ical4j/ical4j
